DATAS SEGMENT
    ;此处输入数据段代码  
    STR1 DB 13,10,"INPUT NAME:",13,10,"$"
    STR2 DB 13,10,"INPUT TELEPHONE NUMBER:",13,10,"$"
    STR3 DB 13,10,"NAME                TEL",13,10,"$"
    
    INBUF DB 20,?,20 DUP(?)
    OUTNAME DB 20,?,20 DUP(?)
    LEN DB ?
    OUTPHONE DB 20,?,20 DUP(?)
DATAS ENDS

STACKS SEGMENT
    ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    MOV ES,AX

    CALL TELIST
    MOV AH,4CH
    INT 21H
INPUT_NAME PROC
    MOV AH,9
    LEA DX,STR1    
    INT 21H
	
    CALL GETCHAR
    MOV CX,BX
    MOV LEN,BL
    LEA SI,INBUF+2
    LEA DI,OUTNAME+2
    CLD
    REP MOVSB
    MOV [BX+OUTNAME+2],BYTE PTR "$"
    RET
INPUT_NAME ENDP

INPUT_PHONE PROC
    MOV AH,9
    LEA DX,STR2
    INT 21H
	
    CALL GETCHAR
    MOV CX,BX
    LEA SI,INBUF+2
    LEA DI,OUTPHONE+2
    CLD
    REP MOVSB
    MOV [BX+OUTPHONE+2],BYTE PTR "$"
    RET
INPUT_PHONE ENDP

GETCHAR PROC
    MOV AH,10
    LEA DX,INBUF
    INT 21H
    MOV BX,0
    MOV BL,INBUF+1
    MOV [BX+INBUF+2],BYTE PTR "$"
    RET
GETCHAR ENDP

PRINTLINE PROC
    MOV AH,9
    LEA DX,STR3
    INT 21H

    MOV AH,9
    LEA DX,OUTNAME+2
    INT 21H

    MOV AX,0
    MOV AL,20
    SUB AL,LEN 
    MOV CX,AX
LP1:
    MOV AH,2
    MOV DL,32
    INT 21H
    LOOPNZ LP1
	    
    MOV AH,9   
    LEA DX,OUTPHONE+2    
    INT 21H
    RET
PRINTLINE ENDP
TELIST PROC
    CALL INPUT_NAME
    CALL INPUT_PHONE
    CALL PRINTLINE
    RET
TELIST ENDP
CODES ENDS
    END START
